FROM python:3.9-slim

WORKDIR /app

# Copiar requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar código do dashboard
COPY app/dashboard/ ./app/dashboard/

# Expor porta
EXPOSE 8501

# Comando para rodar o dashboard
CMD ["streamlit", "run", "app/dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]